addSbtPlugin("org.scoverage"      % "sbt-scoverage"        % "1.5.1")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"          % "0.3.4")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"         % "2.4.3")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"              % "0.4.3")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"         % "0.14.7")
addSbtPlugin("org.scalameta"      % "sbt-native-image"     % "0.3.1")
