name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        scala: [ 2.11.12, 2.12.15, 2.13.7 ]
        java: [ adopt@1.8 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Test the template
        run: sbt --client '++${{ matrix.scala }}; test'